### ISSUE TITLE
selected response font colour

### ISSUE THREAD

**Issue by diana1357** [AskiaADX/DragAndDrop#1]
Hi 

Selected response font colour does not work. Even if I change it for example to white, when I select the response the font colour stays black.
![draganddrop](https://user-images.githubusercontent.com/20987595/31383458-0b8e1b4c-adb3-11e7-87aa-e3927ca5e74b.PNG)

Thanks
Diana

**Comment by Djedj** [comment]
Hi Diana,

Just updated the adc to v2.0.2. Should be fixed now

**Comment by diana1357** [comment]
thank you - looks good
